uploads = []
generated = []

[[outputs]]
id = "aFmcwS20cq6AzksX5M9yG"
uri = "file://nostra-group-build.zip"
type = "unspecified"
title = "Nostra Group — Full Build"

[[outputs]]
id = "fHUy6ZMwgi0Ui2QBUJ8Qe"
uri = "file://nostra-group-build.tar.gz"
type = "unspecified"
title = "Nostra Group — Full Build"

[[outputs]]
id = "4AoinDlguyQ4NWGPpEHGD"
uri = "file://nostra-static-build.tar.gz"
type = "unspecified"
title = "Nostra Group — Static Build (dist/public)"

[[outputs]]
id = "w4Op4qjyvK0dr5yHa-hxl"
uri = "file://nostra-netlify.tar.gz"
type = "unspecified"
title = "Nostra Group — Netlify Build"
